/* ============================================================
   utils/reportExporter.js
   Generates and triggers download of review reports in three
   formats: Markdown, JSON, and HTML.
   ============================================================ */

/**
 * Trigger a file download in the browser.
 * @param {string} filename
 * @param {string} content
 * @param {string} mimeType
 */
function downloadFile(filename, content, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/* ── Shared report metadata ── */
function reportMeta() {
  const score = computeHealthScore();
  const { grade } = scoreToGrade(score);
  const counts = countByType();
  return { score, grade, counts, issues: window.ISSUES || [], date: new Date().toISOString() };
}

/* ══════════════════════════════════════
   MARKDOWN REPORT
   ══════════════════════════════════════ */
function exportMarkdown() {
  const { score, grade, counts, issues, date } = reportMeta();

  const issueLines = issues.map(i => `
### ${i.type.toUpperCase()} · ${i.sev.toUpperCase()} — ${i.title}
- **File:** \`${i.file}:${i.line}\`
- **Description:** ${i.desc}
- **Suggested fix:** \`${i.fix}\`
`).join('');

  const md = `# CodeLens AI — Review Report
**PR:** #142 \`acme-corp/backend\` · **Branch:** \`feat/user-profile-settings\`
**Reviewed:** ${date}

---

## Summary
| Metric | Value |
|--------|-------|
| Health Score | **${score}/100** (Grade **${grade}**) |
| Bugs | ${counts.bug} |
| Security Issues | ${counts.security} |
| Performance Warnings | ${counts.performance} |
| Code Smells | ${counts.smell} |
| Files Reviewed | 12 |

---

## Issues (${issues.length} total)
${issueLines}

---
*Generated by CodeLens AI in 1.8s · 5 agents*
`;

  downloadFile('codelens-review-pr142.md', md, 'text/markdown');
  showToast({ type: 'ok', title: 'Markdown exported', desc: 'codelens-review-pr142.md downloaded.' });
}

/* ══════════════════════════════════════
   JSON REPORT
   ══════════════════════════════════════ */
function exportJSON() {
  const { score, grade, counts, issues, date } = reportMeta();

  const payload = {
    meta: {
      pr          : 142,
      repo        : 'acme-corp/backend',
      branch      : 'feat/user-profile-settings',
      reviewedAt  : date,
      agentCount  : 5,
      durationMs  : 1847,
    },
    summary: { score, grade, counts, filesReviewed: 12 },
    issues  : issues.map(({ id, type, sev, title, desc, file, line, fix }) =>
                ({ id, type, severity: sev, title, description: desc, file, line, suggestedFix: fix })
              ),
  };

  downloadFile(
    'codelens-review-pr142.json',
    JSON.stringify(payload, null, 2),
    'application/json',
  );
  showToast({ type: 'ok', title: 'JSON exported', desc: 'codelens-review-pr142.json downloaded.' });
}

/* ══════════════════════════════════════
   HTML REPORT
   ══════════════════════════════════════ */
function exportHTML() {
  const { score, grade, counts, issues, date } = reportMeta();

  const TYPE_COLORS = {
    bug        : '#E24B4A',
    security   : '#D85A30',
    performance: '#BA7517',
    smell      : '#7F77DD',
  };

  const issueCards = issues.map(i => `
    <div style="border:1px solid #e5e5e5;border-left:4px solid ${TYPE_COLORS[i.type] || '#888'};
                border-radius:8px;padding:1rem;margin-bottom:.75rem;">
      <div style="display:flex;gap:8px;align-items:flex-start;margin-bottom:.5rem">
        <span style="font-size:11px;font-weight:700;background:#f0f0f0;padding:2px 8px;border-radius:10px;">
          ${i.type.toUpperCase()}
        </span>
        <strong style="font-size:14px">${i.title}</strong>
      </div>
      <p style="font-size:13px;color:#555;margin-bottom:.5rem">${i.desc}</p>
      <code style="display:block;background:#f7f7f5;padding:.5rem .75rem;border-radius:6px;
                   font-size:12px;margin-bottom:.5rem">${i.file}:${i.line}</code>
      <p style="font-size:12px;color:#777">💡 Fix: <code>${i.fix}</code></p>
    </div>
  `).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>CodeLens AI — PR #142 Review</title>
  <style>
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
         max-width:760px;margin:2rem auto;padding:0 1rem;color:#1a1a18}
    h1{font-size:22px;margin-bottom:.25rem}
    .meta{color:#777;font-size:13px;margin-bottom:1.5rem}
    .score-box{background:linear-gradient(135deg,#534AB7,#E24B4A);color:#fff;
               border-radius:12px;padding:1.5rem;margin-bottom:1.5rem;display:flex;gap:2rem;align-items:center}
    .score-num{font-size:48px;font-weight:800;line-height:1}
    .grade{font-size:32px;font-weight:800;background:rgba(255,255,255,.2);
           width:56px;height:56px;border-radius:12px;display:flex;align-items:center;justify-content:center}
    .kpi-row{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;margin-bottom:1.5rem}
    .kpi{border:1px solid #e5e5e5;border-radius:8px;padding:.75rem;text-align:center}
    .kpi-val{font-size:22px;font-weight:700}
    .kpi-lbl{font-size:11px;color:#888;margin-top:2px}
    h2{font-size:16px;margin:1.5rem 0 .75rem}
    footer{font-size:11px;color:#aaa;margin-top:2rem;text-align:center}
  </style>
</head>
<body>
  <h1>🔍 CodeLens AI Review Report</h1>
  <div class="meta">PR #142 · acme-corp/backend · Reviewed ${date}</div>

  <div class="score-box">
    <div class="score-num">${score}</div>
    <div>
      <div style="font-size:18px;font-weight:700;margin-bottom:4px">Code Health Score</div>
      <div style="font-size:13px;opacity:.85">5 agents · 1.8s review · 12 files</div>
    </div>
    <div class="grade" style="margin-left:auto">${grade}</div>
  </div>

  <div class="kpi-row">
    <div class="kpi"><div class="kpi-val" style="color:#E24B4A">${counts.bug}</div><div class="kpi-lbl">Bugs</div></div>
    <div class="kpi"><div class="kpi-val" style="color:#D85A30">${counts.security}</div><div class="kpi-lbl">Security</div></div>
    <div class="kpi"><div class="kpi-val" style="color:#BA7517">${counts.performance}</div><div class="kpi-lbl">Performance</div></div>
    <div class="kpi"><div class="kpi-val" style="color:#7F77DD">${counts.smell}</div><div class="kpi-lbl">Smells</div></div>
  </div>

  <h2>Issues (${issues.length})</h2>
  ${issueCards}

  <footer>Generated by CodeLens AI · ${date}</footer>
</body>
</html>`;

  downloadFile('codelens-review-pr142.html', html, 'text/html');
  showToast({ type: 'ok', title: 'HTML report exported', desc: 'codelens-review-pr142.html downloaded.' });
}
